### PR TITLE
Make `spline_knots` a parameter

### LINKED ISSUE #54: Making Spline Knots a tunable knob
Right now we set it to 4, but this number should be allowed to be changed. 

If None:
Then return the LC without this corrector.

### PR DESCRIPTION
**Pull request by tobin-wainer**
Making the splot Knots a tunable knob. 

Default is 5, if 0, returns model without this corrector. 

@TomWagg, does this work for you?

Question: Why is the  "full_model_normalized" a "self." object, and the other models are not? 

This will close #54

### CODE REVIEW

**Comment by tobin-wainer** [comment]
This will solve #54

**Review by TomWagg — COMMENTED** [review]
This looks pretty good to me. My only thought is that usually the way to indicate to not use a parameter is to have it as `None` rather `0` to ensure the type is completely different.

Answer to your question: that's the only model currently in use by the `EnsembleLC` class and so that only one that needs to be accessed externally.

I'll finish reviewing and approve this one properly after we merge #75 so we can disentangle changes between them.

**Comment by tobin-wainer** [comment]
Good call on the none vs 0

**Comment by TomWagg** [comment]
I got the `None` conditions working. One caveat: without the spline fit some of the flux values seems to be negative, so we get warnings about converting them to magnitudes, waiting to talk to discuss what to do about this.

**Pull request merged**
